spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:${POSTGRES_ADDRESS_PORT:6767}/${POSTGRES_DB_NAME:auth}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:${keycloak.url}/realms/${keycloak.realm}}
          jwk-set-uri: ${OAUTH2_JWK:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8181}
  realm: orderflow
  client-id: order-app
  client-secret: ${KEYCLOAK_CLIENT_SECRET:8M5eod18E0CME6I2t6zgUSHMx1nnPHAC}
  admin-username: ${KEYCLOAK_ADMIN:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  send-email: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true