services:

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8761/actuator/health | grep -q UP" ]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: on-failure