services:

  order-db:
    image: postgres:17-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"   # 5433 снаружи, чтобы не конфликтовать с локальным postgres
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d order_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      POSTGRES_ADDRESS: order-db
      POSTGRES_ADDRESS_PORT: 5432
      POSTGRES_DB_NAME: order_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      EUREKA_HOST: eureka-server
      EUREKA_PORT: 8761
      PORT: 8081
    depends_on:
      order-db:
        condition: service_healthy
    restart: on-failure

volumes:
  order-db-data: