spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:${POSTGRES_ADDRESS_PORT:5433}/${POSTGRES_DB_NAME:order_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:${keycloak.url}/realms/${keycloak.realm}}
          jwk-set-uri: ${OAUTH2_JWK:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}

keycloak:
  url: ${KEYCLOAK_URL:http://localhost:8181}
  realm: orderflow
  client-id: order-app
  client-secret: ${KEYCLOAK_CLIENT_SECRET:8M5eod18E0CME6I2t6zgUSHMx1nnPHAC}
  admin-username: ${KEYCLOAK_ADMIN:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
  send-email: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${PORT:8081}
  address: 0.0.0.0
  servlet:
    context-path: /api/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true